// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aczrkjwdanmxoxwajeke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjenJrandkYW5teG94d2FqZWtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjAyNzcsImV4cCI6MjA2OTYzNjI3N30.coPMJLfz8l8qNaVC5vMeQPEHoIox2SmXk8aBU35R66w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});